### ISSUE TITLE
Window mode crashed on tiling window manager

### ISSUE THREAD

**Issue by raoulb** [Enigma-Game/Enigma#98]
Running Enigma in window mode on a tiling window manager (at least for me) crashes the application reliably at the end of the startup sequence, always on the same line:

```
Thread 1 "enigma" received signal SIGSEGV, Segmentation fault.
ecl::Scaler::blit_scaled (this=<optimized out>, src=<optimized out>, srcrect=<optimized out>, dst=<optimized out>, dstrect=<optimized out>) at ecl_video.cc:615
615                 t1 = ((((c01->r - c00->r) * ex) >> 16) + c00->r) & 0xff;
```

Backtrace:
```
(gdb) bt

#0  ecl::Scaler::blit_scaled (this=<optimized out>, src=<optimized out>, srcrect=<optimized out>, dst=<optimized out>, dstrect=<optimized out>) at ecl_video.cc:615
#1  0x00005555557a993d in ecl::Screen::flush_updates (this=0x555555ce7b10) at ecl_video.cc:410
#2  0x00005555556f6b65 in enigma::gui::Menu::manage (this=this@entry=0x7fffffffdc20) at gui/Menu.cc:94
#3  0x00005555556f5cf5 in enigma::gui::ShowMainMenu () at gui/MainMenu.cc:577
#4  0x00005555555f5bd8 in main (argc=<optimized out>, argv=<optimized out>) at main.cc:992
```

I will provide a better backtrace after I compiled Enigma with debug symbols.

My guess is that something here does not cope well with an externally forced window size other than what the application wishes to run in.

**Comment by alochmann** [comment]
Which tiling window manager are you using? Full-screen or windowed? If windowed, are there other windows open?

I tried kwin-bismuth (on KDE-Plasma), and Enigma does not crash. It does not work either at first (missing scaling and the mouse isn't captured, which points at an SDL bug), but after moving and retiling there are no problems. Though, it is a little "out of shape", as is to be expected under these circumstances.
